version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION=host=${DB_HOST} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} port=${DB_PORT} sslmode=disable
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    entrypoint: >
      sh -c "until nc -z db 5432; do echo 'Esperando pelo banco de dados...'; sleep 1; done;
      go run main.go"  # Aguarda até que o banco de dados esteja pronto antes de iniciar a aplicação

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
